import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const credentialStyles = readFileSync(new URL('../CredentialSections.module.scss', import.meta.url), 'utf8')
const themeStyles = readFileSync(new URL('../../../../styles/themes.scss', import.meta.url), 'utf8')
const credentialShellSource = readFileSync(new URL('../CredentialSectionShell.tsx', import.meta.url), 'utf8')
const credentialHealthSource = readFileSync(new URL('../CredentialHealthPanel.tsx', import.meta.url), 'utf8')
const aiProviderSectionSource = readFileSync(new URL('../AiProviderCredentialsSection.tsx', import.meta.url), 'utf8')
const authFileSectionSource = readFileSync(new URL('../AuthFileCredentialsSection.tsx', import.meta.url), 'utf8')

const cssBlock = (selector: string) => {
  const start = credentialStyles.indexOf(selector)
  expect(start).toBeGreaterThanOrEqual(0)
  const next = credentialStyles.indexOf('\n.', start + selector.length)
  return credentialStyles.slice(start, next === -1 ? undefined : next)
}

describe('Credential section styles', () => {
  it('renders the credential count as a quiet theme-aware badge', () => {
    expect(credentialShellSource).toContain('className={styles.credentialCountBadge}')
    expect(credentialStyles).toMatch(/\.credentialCountBadge:global\(\.ant-tag\)\s*\{[\s\S]*?background:\s*var\(--count-badge-bg\);/)
    expect(credentialStyles).toMatch(/\.credentialCountBadge:global\(\.ant-tag\)\s*\{[\s\S]*?color:\s*var\(--count-badge-text\);/)
    expect(credentialStyles).toMatch(/\.credentialCountBadge:global\(\.ant-tag\)\s*\{[\s\S]*?border:\s*1px solid var\(--border-secondary\);/)
    expect(themeStyles).toMatch(/\[data-theme='white'\][\s\S]*?--count-badge-bg:\s*var\(--surface-inset\);/)
    expect(themeStyles).toMatch(/\[data-theme='dark'\][\s\S]*?--count-badge-text:\s*var\(--text-secondary\);/)
  })

  it('uses matching Ant Design tables for Auth Files and AI Provider rows', () => {
    expect(authFileSectionSource).toContain('TableColumnsType<AuthFileCredentialRow>')
    expect(authFileSectionSource).toContain('<Table<AuthFileCredentialRow>')
    expect(aiProviderSectionSource).toContain('TableColumnsType<AiProviderCredentialRow>')
    expect(aiProviderSectionSource).toContain('<Table<AiProviderCredentialRow>')
    expect(authFileSectionSource).toContain('pagination={false}')
    expect(aiProviderSectionSource).toContain('pagination={false}')
    expect(authFileSectionSource).toContain('row.identity.id || row.identity.identity')
    expect(aiProviderSectionSource).toContain('row.identity.id || row.identity.identity')
    expect(authFileSectionSource).toMatch(/key: 'name',[\s\S]*?width: 216,[\s\S]*?key: 'provider',[\s\S]*?width: 92,[\s\S]*?key: 'quotaOrHealth',[\s\S]*?width: showHealthMode \? 430 : 340,/)
    expect(aiProviderSectionSource).toMatch(/key: 'name',[\s\S]*?width: 216,[\s\S]*?key: 'provider',[\s\S]*?width: 92,[\s\S]*?key: 'health',[\s\S]*?width: 430,/)
    expect(authFileSectionSource).toContain('scroll={{ x: showHealthMode ? 1222 : 1132 }}')
    expect(aiProviderSectionSource).toContain('scroll={{ x: 1178 }}')
    expect(authFileSectionSource).not.toContain('<CredentialBadge>')
    expect(aiProviderSectionSource).not.toContain('<CredentialBadge>')
    expect(credentialStyles).toContain('.credentialDataTable:global(.ant-table-wrapper)')
    expect(credentialShellSource).not.toContain('CredentialRowShell')
    expect(credentialShellSource).not.toContain('CredentialTableHeader')
    expect(authFileSectionSource).toContain('<AuthFileDisplayModeSwitch')
    expect(authFileSectionSource).toContain('readStoredAuthFileDisplayMode')
    expect(authFileSectionSource).toContain('persistAuthFileDisplayMode(mode)')
    expect(authFileSectionSource).toContain("value: 'quota'")
    expect(authFileSectionSource).toContain("displayMode === 'health'")
    expect(authFileSectionSource).not.toContain('mockCredentialsMode')
    expect(authFileSectionSource).not.toContain('isMockCredentialsMode')
    expect(authFileSectionSource).toContain('CredentialHealthPanel')
    expect(authFileSectionSource).toContain('lastUsedAt={row.identity.last_used_at}')
    expect(authFileSectionSource).toContain('statsUpdatedAt={row.identity.stats_updated_at}')
    expect(aiProviderSectionSource).toContain('CredentialHealthPanel')
    expect(aiProviderSectionSource).toContain('lastUsedAt={row.lastUsedText}')
    expect(aiProviderSectionSource).toContain('statsUpdatedAt={row.statsUpdatedText}')
    expect(aiProviderSectionSource).not.toContain('DisplayModeSwitch')
  })

  it('lets Auth Files quota bars wrap before their blocks overlap', () => {
    expect(authFileSectionSource).toMatch(/key: 'quotaOrHealth',[\s\S]*?width: showHealthMode \? 430 : 340,/)
    expect(credentialStyles).toMatch(/\.credentialQuotaSideWithAction\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\) 30px;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaSideWithAction\s*\{[\s\S]*?gap:\s*14px;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaBars\s*\{[\s\S]*?grid-template-columns:\s*repeat\(2, minmax\(0, 131px\)\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaBars\s*\{[\s\S]*?gap:\s*10px;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaBarBlock\s*\{[\s\S]*?width:\s*131px;[\s\S]*?min-width:\s*0;/)
    expect(authFileSectionSource).toContain('Table.EXPAND_COLUMN')
    expect(authFileSectionSource.indexOf('Table.EXPAND_COLUMN')).toBeLessThan(authFileSectionSource.indexOf("key: 'name'"))
    expect(authFileSectionSource).toContain('columnWidth: 44')
    expect(authFileSectionSource).not.toContain("fixed: 'right'")
    expect(authFileSectionSource).toContain('className={styles.credentialRowExpandButton}')
    expect(authFileSectionSource).toContain("{expanded ? '−' : '+'}")
    expect(credentialStyles).toMatch(/\.credentialRowExpandButton\s*\{[\s\S]*?width:\s*24px;[\s\S]*?height:\s*24px;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaDetailGrid\s*\{[\s\S]*?grid-template-columns:\s*minmax\(150px, 1\.4fr\) 140px 90px 110px 124px 124px;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaDetailProgress\s*\{[\s\S]*?grid-template-columns:\s*minmax\(72px, 1fr\) 36px;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaDetailValue\s*\{[\s\S]*?justify-content:\s*flex-end;[\s\S]*?white-space:\s*nowrap;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaGroupLabel\s*\{[\s\S]*?color:\s*var\(--text-tertiary\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaGroupTooltip\s*\{[\s\S]*?opacity:\s*0;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaGroupTooltipTarget\s*\{[\s\S]*?cursor:\s*default;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaGroupTooltip\s*\{[\s\S]*?max-width:\s*min\(240px, 70vw\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaGroupTooltip\s*\{[\s\S]*?overflow-wrap:\s*anywhere;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaGroupTooltipTarget \.credentialQuotaGroupTooltip\s*\{[\s\S]*?white-space:\s*normal;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaGroupTooltipTarget:hover \.credentialQuotaGroupTooltip[\s\S]*?opacity:\s*1;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaGroupTooltipTarget:focus-visible \.credentialQuotaGroupTooltip[\s\S]*?opacity:\s*1;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaDetailRow \.credentialQuotaGroupTooltip\s*\{[\s\S]*?right:\s*0;[\s\S]*?left:\s*auto;/)
    expect(authFileSectionSource).toContain('<Segmented<AuthFileDisplayMode>')
    expect(authFileSectionSource).toContain("value: 'health'")
    expect(credentialStyles).not.toContain('.credentialDisplayModeSwitcher')
    expect(authFileSectionSource).toContain('className={styles.credentialQuotaProgress}')
    expect(authFileSectionSource).toContain('strokeColor={quotaProgressColor(quota.status)}')
    expect(credentialStyles).toContain('.credentialQuotaProgress:global(.ant-progress)')
    expect(credentialStyles).not.toContain('.credentialQuotaTrack')
    expect(credentialStyles).not.toContain('.credentialQuotaFill')
    expect(cssBlock('.credentialHealthGrid')).toContain('grid-template-columns: repeat(30, 4px);')
    expect(cssBlock('.credentialHealthGrid')).toContain('gap: 4px;')
    expect(credentialStyles).toMatch(/\.credentialHealthCell\s*\{[\s\S]*?width:\s*4px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCell\s*\{[\s\S]*?box-shadow:\s*none;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCell\s*\{[\s\S]*?cursor:\s*default;/)
    expect(cssBlock('.credentialHealthCell')).not.toContain('cursor: help;')
    expect(credentialStyles).toMatch(/\.credentialHealthCellSuccess\s*\{[\s\S]*?background:\s*var\(--success-color\);/)
    expect(credentialStyles).toMatch(/\.credentialHealthCellWarning\s*\{[\s\S]*?background:\s*var\(--quota-medium-color\);/)
    expect(credentialStyles).toMatch(/\.credentialHealthCellFailure\s*\{[\s\S]*?background:\s*var\(--danger-color\);/)
    expect(credentialStyles).toMatch(/\.credentialHealthCellEmpty\s*\{[\s\S]*?background:\s*var\(--bg-tertiary\);/)
    expect(cssBlock('.credentialHealthCellSuccess')).not.toContain('height:')
    expect(cssBlock('.credentialHealthCellWarning')).not.toContain('height:')
    expect(cssBlock('.credentialHealthCellFailure')).not.toContain('height:')
    expect(cssBlock('.credentialHealthCellEmpty')).not.toContain('height:')
    expect(credentialHealthSource).toContain('style={{ height: `${bucket.heightPx}px` }}')
    expect(cssBlock('.credentialHealthMetaUnhealthy .credentialHealthMetaStatus')).toContain('color: var(--danger-color);')
    expect(cssBlock('.credentialHealthCellSuccess')).not.toContain('linear-gradient')
    expect(cssBlock('.credentialHealthCellWarning')).not.toContain('linear-gradient')
    expect(cssBlock('.credentialHealthCellFailure')).not.toContain('linear-gradient')
    expect(credentialStyles).not.toContain('credentialQuotaChips')
    expect(credentialStyles).not.toContain('credentialQuotaChip')
    expect(credentialStyles).not.toContain('credentialQuotaSidePanel')
    expect(credentialStyles).not.toContain('credentialQuotaRow')
    expect(credentialStyles).toMatch(/\.credentialHealthPanel\s*\{[\s\S]*?display:\s*grid;/)
    expect(credentialStyles).toMatch(/\.credentialHealthPanel\s*\{[\s\S]*?grid-template-columns:\s*max-content minmax\(160px, 1fr\);/)
    expect(credentialStyles).toMatch(/\.credentialHealthPanel\s*\{[\s\S]*?column-gap:\s*40px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthChart\s*\{[\s\S]*?width:\s*max-content;/)
    expect(credentialStyles).toMatch(/\.credentialHealthMeta\s*\{[\s\S]*?flex-direction:\s*column;/)
    expect(credentialStyles).toMatch(/\.credentialHealthMeta\s*\{[\s\S]*?gap:\s*7px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthMetaTimes\s*\{[\s\S]*?display:\s*flex;/)
    expect(credentialStyles).toMatch(/\.credentialHealthMetaTimes\s*\{[\s\S]*?gap:\s*10px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthMetaTime\s*\{[\s\S]*?display:\s*inline-flex;/)
    expect(credentialStyles).toMatch(/\.credentialHealthMetaTimeIcon\s*\{[\s\S]*?width:\s*11px;/)
    expect(credentialStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.credentialHealthPanel\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\);/)
    expect(credentialHealthSource).toContain('credentialHealthChart')
    expect(credentialHealthSource).toContain('credentialHealthMeta')
    expect(credentialHealthSource).toContain('IconTimer')
    expect(credentialHealthSource).toContain('IconRefreshCw')
  })

  it('uses Ant Design switches for Auth Files toggles', () => {
    expect(authFileSectionSource).toMatch(/credentials_auth_files_active_only[\s\S]*?<Switch[\s\S]*?checked=\{activeOnly\}[\s\S]*?onChange=\{onActiveOnlyChange\}/)
    expect(authFileSectionSource).toMatch(/credentials_auto_refresh_enabled[\s\S]*?<Switch[\s\S]*?checked=\{enabled\}[\s\S]*?onChange=\{onEnabledChange\}/)
    expect(authFileSectionSource).toContain('disabled={controlsDisabled}')
    expect(authFileSectionSource).toContain('size="small"')
    expect(authFileSectionSource).not.toContain('credentialActiveOnlyTrack')
    expect(authFileSectionSource).not.toContain('credentialActiveOnlyThumb')
    expect(credentialStyles).not.toContain('.credentialActiveOnlySwitch')
    expect(credentialStyles).not.toContain('.credentialActiveOnlyTrack')
    expect(credentialStyles).not.toContain('.credentialActiveOnlyThumb')
    expect(themeStyles).toMatch(/:root\s*\{[\s\S]*?--text-primary:\s*#192230;/)
    expect(themeStyles).toMatch(/\[data-theme='white'\]\s*\{[\s\S]*?--bg-primary:\s*#ffffff;/)
  })

  it('keeps scheduled refresh controls stable, clear, and compact', () => {
    const scheduleGridStyles = cssBlock('.credentialAutoRefreshScheduleGrid')
    const unitSwitcherStyles = cssBlock('.credentialAutoRefreshUnitSwitcher')
    const intervalFieldStyles = cssBlock('.credentialAutoRefreshIntervalField')
    const tipStyles = cssBlock('.credentialAutoRefreshScheduleTip')

    expect(authFileSectionSource).toContain('credentialAutoRefreshScheduleArea')
    expect(authFileSectionSource).toContain('credentialAutoRefreshScheduleAreaActive')
    expect(authFileSectionSource).toContain('credentialAutoRefreshIntervalField')
    expect(authFileSectionSource).toContain('credentialAutoRefreshUnitSuffix')
    expect(authFileSectionSource).not.toContain('credentialAutoRefreshField')
    expect(authFileSectionSource).toContain('width={620}')
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshSettingsModal\s*\{[\s\S]*?max-width:\s*min\(620px, calc\(100vw - 28px\)\);/)
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshScheduleArea\s*\{[\s\S]*?grid-template-rows:\s*0fr;/)
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshScheduleArea\s*\{[\s\S]*?transition:\s*grid-template-rows 0\.18s ease, opacity 0\.16s ease;/)
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshScheduleAreaActive\s*\{[\s\S]*?grid-template-rows:\s*1fr;/)
    expect(scheduleGridStyles).toContain('grid-template-columns: minmax(300px, 1fr) 256px;')
    expect(scheduleGridStyles).toContain('column-gap: 8px;')
    expect(scheduleGridStyles).toContain('align-items: center;')
    expect(scheduleGridStyles).toContain('overflow: visible;')
    expect(unitSwitcherStyles).toContain('grid-template-columns: repeat(4, minmax(0, 1fr));')
    expect(unitSwitcherStyles).toContain('width: 100%;')
    expect(unitSwitcherStyles).toContain('white-space: nowrap;')
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshUnitButtonActive\s*\{[\s\S]*?background:\s*linear-gradient\(135deg, var\(--primary-color\), var\(--primary-hover\)\) !important;/)
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshUnitButtonActive\s*\{[\s\S]*?color:\s*var\(--primary-contrast, #fff\) !important;/)
    expect(intervalFieldStyles).toContain('grid-template-columns: 64px 100px 68px;')
    expect(intervalFieldStyles).toContain('align-items: center;')
    expect(intervalFieldStyles).toContain('justify-self: end;')
    expect(intervalFieldStyles).toContain('column-gap: 12px;')
    expect(intervalFieldStyles).toContain('width: 256px;')
    expect(intervalFieldStyles).toContain('max-width: 100%;')
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshIntervalField\s*\{[\s\S]*?input,\s*select\s*\{[\s\S]*?min-height:\s*40px;/)
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshIntervalField\s*\{[\s\S]*?input,\s*select\s*\{[\s\S]*?text-align:\s*center;/)
    expect(intervalFieldStyles).toMatch(/select\s*\{[\s\S]*?grid-column:\s*span 2;/)
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshIntervalLabel\s*\{[\s\S]*?text-align:\s*right;/)
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshUnitSuffix\s*\{[\s\S]*?text-align:\s*left;/)
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshUnitSuffix\s*\{[\s\S]*?overflow:\s*visible;/)
    expect(credentialStyles).toMatch(/\.credentialAutoRefreshUnitSuffix\s*\{[\s\S]*?text-overflow:\s*clip;/)
    expect(authFileSectionSource).toContain('credentialAutoRefreshScheduleTip')
    expect(tipStyles).toContain('margin-top: 8px;')
    expect(tipStyles).toContain('font-size: 12px;')
    expect(tipStyles).toContain('line-height: 1.45;')
  })

  it('renders Auth Files health buckets as compact hover detail targets', () => {
    expect(credentialHealthSource).toContain('usage_stats.credentials_health_grid_aria')
    expect(credentialHealthSource).toContain('usage_stats.credentials_health_bucket_aria')
    expect(credentialHealthSource).toContain('bucket.successCount')
    expect(credentialHealthSource).toContain('bucket.failureCount')
    expect(credentialHealthSource).toContain('credentialHealthTooltip')
    expect(credentialHealthSource).toMatch(/<span[\s\S]*?role="listitem"[\s\S]*?className=\{`\$\{styles\.credentialHealthCell/)
    expect(credentialStyles).toMatch(/\.credentialHealthCell\s*\{[\s\S]*?position:\s*relative;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCell\s*\{[\s\S]*?border:\s*0;/)
    expect(cssBlock('.credentialHealthCell')).toContain('cursor: default;')
    expect(credentialStyles).toMatch(/\.credentialHealthCell\s*\{[\s\S]*?transition:\s*transform 0\.16s ease/)
    expect(credentialStyles).toMatch(/\.credentialHealthCell\s*\{[\s\S]*?border-radius:\s*3px;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCell:hover[\s\S]*?transform:\s*translateY\(-2px\) scale\(1\.2\);/)
    expect(credentialStyles).toMatch(/\.credentialHealthTooltip\s*\{[\s\S]*?position:\s*absolute;/)
    expect(credentialStyles).toMatch(/\.credentialHealthTooltip\s*\{[\s\S]*?font-size:\s*var\(--type-caption-size\);/)
    expect(credentialStyles).toMatch(/\.credentialHealthTooltip\s*\{[\s\S]*?font-weight:\s*400;/)
    expect(credentialStyles).toMatch(/\.credentialHealthTooltip\s*\{[\s\S]*?opacity:\s*0;/)
    expect(credentialStyles).toMatch(/\.credentialHealthCell:hover \.credentialHealthTooltip[\s\S]*?opacity:\s*1;/)
    expect(credentialStyles).not.toMatch(/\.credentialHealthCell:focus-visible/)
    expect(credentialHealthSource).not.toMatch(/<button[\s\S]*?credentialHealthCell/)
  })

  it('transforms semantic table rows from their available container width', () => {
    expect(credentialStyles).toMatch(/\.credentialRows\s*\{[\s\S]*?container-name:\s*credential-data-layout;[\s\S]*?container-type:\s*inline-size;/)
    expect(credentialStyles).toMatch(/@container credential-data-layout \(max-width: 1024px\)\s*\{[\s\S]*?:global\(\.ant-table-thead\)\s*\{[\s\S]*?display:\s*none;/)
    expect(credentialStyles).toMatch(/@container credential-data-layout \(max-width: 1024px\)\s*\{[\s\S]*?:global\(\.ant-table-tbody > tr\)\s*\{[\s\S]*?grid-template-columns:\s*repeat\(4, minmax\(0, 1fr\)\);/)
    expect(credentialStyles).toMatch(/@container credential-data-layout \(max-width: 768px\)\s*\{[\s\S]*?:global\(\.ant-table-tbody > tr\)\s*\{[\s\S]*?grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\);/)
    expect(credentialStyles).toMatch(/@container credential-data-layout \(max-width: 480px\)\s*\{[\s\S]*?:global\(\.ant-table-tbody > tr\)\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\);/)
    expect(credentialStyles).toMatch(/\.credentialResponsiveCellLabel\s*\{[\s\S]*?display:\s*none;/)
    expect(credentialStyles).toMatch(/@container credential-data-layout \(max-width: 1024px\)\s*\{[\s\S]*?\.credentialResponsiveCellLabel\s*\{[\s\S]*?display:\s*block;/)
    expect(credentialStyles).toMatch(/:global\(\.ant-table-tbody > tr > td\)\s*\{[\s\S]*?min-width:\s*0;[\s\S]*?max-width:\s*100%;/)
    expect(credentialStyles).toMatch(/:global\(\.ant-table-tbody > tr > td > \*\)\s*\{[\s\S]*?min-width:\s*0;[\s\S]*?max-width:\s*100%;/)
    expect(credentialStyles).toMatch(/\.credentialIdentityBlock,\s*\n\.credentialTableCellContent,\s*\n\.credentialSidePanel\s*\{[\s\S]*?min-width:\s*0;[\s\S]*?max-width:\s*100%;/)
    expect(credentialStyles).toMatch(/@container credential-data-layout \(max-width: 1024px\)\s*\{[\s\S]*?\.credentialNameTableCell,\s*\n\s*\.credentialSideTableCell\s*\{[\s\S]*?grid-column:\s*1 \/ -1;/)
    expect(credentialStyles).toMatch(/@container credential-data-layout \(max-width: 1024px\)\s*\{[\s\S]*?\.credentialQuotaSideWithAction\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\) 30px;/)
    expect(credentialStyles).toMatch(/@container credential-data-layout \(max-width: 1024px\)\s*\{[\s\S]*?\.credentialQuotaBars\s*\{[\s\S]*?grid-template-columns:\s*repeat\(2, minmax\(0, 131px\)\);/)
    expect(credentialStyles).toMatch(/@container credential-data-layout \(max-width: 1024px\)\s*\{[\s\S]*?\.credentialQuotaBarBlock\s*\{[\s\S]*?min-width:\s*0;[\s\S]*?max-width:\s*100%;/)
  })

  it('stacks Auth Files quota error status above the message', () => {
    expect(credentialStyles).toMatch(/\.credentialQuotaErrorSummary\s*\{[\s\S]*?flex-direction:\s*column;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaErrorSummary\s*\{[\s\S]*?align-items:\s*flex-start;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaErrorMessage\s*\{[\s\S]*?white-space:\s*normal;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaErrorMessage\s*\{[\s\S]*?line-height:\s*1\.35;/)
  })

  it('keeps Auth Files quota actions inside narrow transformed rows', () => {
    expect(credentialStyles).toMatch(/@container credential-data-layout \(max-width: 480px\)\s*\{[\s\S]*?\.credentialQuotaSideWithAction\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\) auto;/)
    expect(credentialStyles).toMatch(/@container credential-data-layout \(max-width: 480px\)\s*\{[\s\S]*?\.credentialQuotaBars\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 131px\);/)
    expect(credentialStyles).toMatch(/@container credential-data-layout \(max-width: 1024px\)\s*\{[\s\S]*?\.credentialQuotaBarBlock\s*\{[\s\S]*?min-width:\s*0;/)
  })

  it('renders compact Ant Design priority tags without lengthening credential names', () => {
    expect(credentialStyles).toMatch(/\.credentialPriorityBadge\s*\{[\s\S]*?margin-inline-end:\s*0;/)
    expect(credentialStyles).toMatch(/\.credentialPriorityBadge\s*\{[\s\S]*?min-width:\s*24px;/)
    expect(credentialShellSource).toContain('<Tag color="blue" variant="filled" className={styles.credentialPriorityBadge}>')
    expect(credentialShellSource).toContain('CredentialPriorityBadge')
    expect(authFileSectionSource).toContain('row.priorityLabel')
    expect(authFileSectionSource).toMatch(/row\.planTypeLabel[\s\S]*?row\.remainingDaysLabel[\s\S]*?row\.priorityLabel/)
    expect(aiProviderSectionSource).toContain('row.priorityLabel')
  })

  it('renders provider identity as a plain dedicated table column', () => {
    expect(authFileSectionSource).toContain('className={styles.credentialProviderValue}')
    expect(aiProviderSectionSource).toContain('className={styles.credentialProviderValue}')
    expect(credentialStyles).toMatch(/\.credentialProviderValue\s*\{[\s\S]*?display:\s*block;[\s\S]*?text-overflow:\s*ellipsis;/)
    expect(credentialShellSource).not.toContain('CredentialBadge')
    expect(credentialStyles).not.toContain('.credentialBadgeNeutral')
  })

  it('keeps credential alias edit buttons in a fixed name-cell action slot', () => {
    expect(credentialStyles).toMatch(/\.credentialNameRow\s*\{[\s\S]*?max-width:\s*196px;/)
    expect(credentialStyles).toMatch(/\.credentialDisplayName\s*\{[\s\S]*?display:\s*block;[\s\S]*?max-width:\s*196px;/)
    expect(credentialStyles).toMatch(/\.credentialAliasEditor\s*\{[\s\S]*?max-width:\s*196px;/)
    expect(credentialStyles).toMatch(/\.credentialAliasDisplayLayout\s*\{[\s\S]*?display:\s*grid;/)
    expect(credentialStyles).toMatch(/\.credentialAliasDisplayLayout\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\) 28px;/)
    expect(credentialStyles).toMatch(/\.credentialAliasDisplayLayout\s*\{[\s\S]*?column-gap:\s*8px;/)
    expect(credentialStyles).toMatch(/\.credentialAliasNameSlot\s*\{[\s\S]*?min-width:\s*0;/)
    expect(credentialStyles).toMatch(/\.credentialAliasNameSlot\s*\{[\s\S]*?display:\s*block;[\s\S]*?text-overflow:\s*ellipsis;[\s\S]*?white-space:\s*nowrap;/)
    expect(authFileSectionSource).toContain('<AccessibleEllipsis value={row.displayName} />')
    expect(aiProviderSectionSource).toContain('<AccessibleEllipsis value={row.displayName} />')
    expect(credentialShellSource).toContain("trigger={['hover', 'focus', 'click']}")
    expect(credentialStyles).toMatch(/\.credentialAliasActionSlot\s*\{[\s\S]*?width:\s*24px;/)
    expect(credentialStyles).toMatch(/\.credentialAliasActionSlot\s*\{[\s\S]*?justify-self:\s*start;/)
    expect(credentialStyles).not.toMatch(/\.credentialAliasDisplay\s*\{/)
  })

  it('keeps Auth Files inspection separate from the quota refresh pill', () => {
    expect(authFileSectionSource).toContain('credentialSectionActionButtons')
    expect(authFileSectionSource).toMatch(/credentialInspectionSwitcher[\s\S]*?credentialInspectionButton[\s\S]*?credentialRefreshSwitcher/)
    expect(authFileSectionSource).toContain('credentialInspectionButton')
    expect(authFileSectionSource).toMatch(/credentialInspectionButton[\s\S]*?credentialRefreshSwitcher/)
    expect(authFileSectionSource).toMatch(/credentialRefreshSwitcher\} \$\{styles\.credentialInspectionSwitcher[\s\S]*?credentialInspectionButton[\s\S]*?<\/div>\s*<div className=\{styles\.credentialRefreshSwitcher\}>[\s\S]*?credentialRefreshButtonLoading/)
    expect(credentialStyles).toMatch(/\.credentialInspectionSwitcher\s*\{[\s\S]*?border-radius:\s*999px;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionSwitcher\s*\{[\s\S]*?background:\s*color-mix\(in srgb, var\(--bg-secondary\) 78%, transparent\);/)
    expect(authFileSectionSource).toContain('<Progress')
    expect(authFileSectionSource).toContain('className={styles.credentialInspectionProgress}')
    expect(authFileSectionSource).toContain('strokeColor="var(--success-color)"')
    expect(authFileSectionSource).toContain("size={['100%', 8]}")
    expect(authFileSectionSource).toContain('railColor="var(--bg-tertiary)"')
    expect(credentialStyles).toMatch(/\.credentialInspectionProgress:global\(\.ant-progress\)\s*\{[\s\S]*?border:\s*1px solid var\(--border-color\);/)
    expect(credentialStyles).not.toContain('.credentialInspectionProgressFill')
    expect(credentialStyles).toMatch(/\.credentialInspectionSummary\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 80px\) minmax\(260px, 1fr\) auto;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionSummary\s*\{[\s\S]*?align-items:\s*start;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionSummary\s*\{[\s\S]*?gap:\s*40px;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionSummary\s*\{[\s\S]*?padding-bottom:\s*34px;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionMetric\s*\{[\s\S]*?align-self:\s*start;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionMetric\s*\{[\s\S]*?align-content:\s*start;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionStartButton\s*\{[\s\S]*?align-self:\s*center;/)
    expect(cssBlock('.credentialInspectionStatCardUnauthorized')).toContain('color: var(--danger-color);')
    expect(cssBlock('.credentialInspectionStatCardLimitReached')).toContain('color: var(--quota-medium-color);')
    expect(cssBlock('.credentialInspectionStatusUnauthorized')).toContain('background: color-mix(in srgb, var(--danger-color) 12%, transparent);')
    expect(cssBlock('.credentialInspectionStatusUnauthorized')).toContain('color: var(--danger-color);')
    expect(cssBlock('.credentialInspectionStatusLimitReached')).toContain('background: color-mix(in srgb, var(--quota-medium-color) 16%, transparent);')
    expect(cssBlock('.credentialInspectionStatusLimitReached')).toContain('color: var(--quota-medium-color);')
    expect(authFileSectionSource).toContain('status?.completed_at')
    expect(authFileSectionSource).toContain('credentials_inspection_limit_reached')
    expect(authFileSectionSource).toContain('credentials_inspection_401_402')
    expect(authFileSectionSource).toContain('credentials_inspection_unknown')
    expect(authFileSectionSource).not.toContain('<small>{result.auth_index}</small>')
    expect(authFileSectionSource).toContain('result.name || result.file_name')
    expect(credentialStyles).toMatch(/\.credentialInspectionStatsGrid\s*\{[\s\S]*?grid-template-columns:\s*repeat\(5, minmax\(0, 1fr\)\);/)
    expect(cssBlock('.credentialInspectionStatCardUnknown')).toContain('color: var(--text-secondary);')
    expect(credentialStyles).not.toContain('.credentialInspectionStatCardPayment')
    expect(authFileSectionSource).toContain('percent={progress}')
    expect(authFileSectionSource).toContain('showInfo={false}')
    expect(authFileSectionSource).toContain("credentials_inspection_progress_aria")
    expect(authFileSectionSource).toContain('buildInspectionResultsPage')
    expect(authFileSectionSource).toContain('nextInspectionResultStatusFilter')
    expect(authFileSectionSource).toContain('INSPECTION_RESULT_PAGE_SIZE_OPTIONS')
    expect(authFileSectionSource).toContain('credentialInspectionStatButton')
    expect(authFileSectionSource).toContain('credentialInspectionResultsFooter')
    expect(authFileSectionSource).not.toContain('results.slice(0, 8)')
    expect(authFileSectionSource).not.toContain('status?.payment_required_402 ?? 0')
    expect(authFileSectionSource).not.toContain('filterStatus="payment_required_402"')
    expect(authFileSectionSource).toContain('<Table<UsageQuotaInspectionResult>')
    expect(authFileSectionSource).toContain('pagination={false}')
    expect(authFileSectionSource).toContain('showHeader={false}')
    expect(authFileSectionSource).toContain('scroll={{ x: 620, y: 420 }}')
    expect(authFileSectionSource).toContain('<Pagination')
    expect(authFileSectionSource).toContain('showSizeChanger')
    expect(credentialStyles).toMatch(/\.credentialInspectionResultsTable:global\(\.ant-table-wrapper\)\s*\{[\s\S]*?:global\(\.ant-table-body\)\s*\{[\s\S]*?scrollbar-width:\s*thin;/)
    expect(credentialStyles).toMatch(/\.credentialInspectionResultsFooter\s*\{[\s\S]*?justify-content:\s*flex-end;/)
    expect(credentialStyles).not.toContain('.credentialInspectionPageSizeControl')
    expect(credentialStyles).not.toContain('.credentialInspectionPagination')
  })


  it('stacks Auth Files quota reset and refresh actions on the right side', () => {
    expect(authFileSectionSource).toContain('credentialQuotaActionStack')
    expect(authFileSectionSource).toContain('credentialRowResetButton')
    expect(credentialStyles).toMatch(/\.credentialQuotaSideWithAction\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\) 30px;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaActionStack\s*\{[\s\S]*?flex-direction:\s*column;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaActionStack\s*\{[\s\S]*?justify-content:\s*center;/)
    expect(credentialStyles).toMatch(/\.credentialRowResetButton\s*\{[\s\S]*?background:\s*var\(--bg-secondary\);/)
    expect(credentialStyles).toMatch(/@container credential-data-layout \(max-width: 480px\)\s*\{[\s\S]*?\.credentialQuotaSideWithAction\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\) auto;/)
    expect(credentialStyles).toMatch(/@container credential-data-layout \(max-width: 480px\)\s*\{[\s\S]*?\.credentialQuotaSideWithAction\s*\{[\s\S]*?gap:\s*10px;/)
  })

  it('keeps Auth Files quota reset popovers visible outside the Ant Design card body', () => {
    expect(authFileSectionSource).toContain('credentialQuotaResetPopover')
    expect(credentialStyles).toMatch(/\.credentialSectionCard:global\(\.ant-card\)\s*\{[\s\S]*?overflow:\s*hidden;/)
    expect(credentialStyles).toMatch(/\.credentialSectionCard:global\(\.ant-card\)\s*\{[\s\S]*?:global\(\.ant-card-body\)\s*\{[\s\S]*?padding:\s*0;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetAction\s*\{[\s\S]*?position:\s*relative;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetPopover\s*\{[\s\S]*?position:\s*fixed;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetPopover\s*\{[\s\S]*?max-height:\s*calc\(100vh - 24px\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetPopover\s*\{[\s\S]*?overflow-y:\s*auto;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetExpiryList\s*\{[\s\S]*?max-height:\s*min\(40vh, 220px\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetExpiryList\s*\{[\s\S]*?overflow-y:\s*auto;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetActions\s*\{[\s\S]*?flex-shrink:\s*0;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetTooltip\s*\{[\s\S]*?position:\s*absolute;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetTooltip\s*\{[\s\S]*?right:\s*calc\(100% \+ 8px\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetAction:hover \.credentialQuotaResetTooltip[\s\S]*?opacity:\s*1;/)
    expect(credentialStyles).not.toContain('.credentialQuotaResetAction:focus-within .credentialQuotaResetTooltip')
    expect(credentialStyles).toMatch(/\.credentialQuotaResetCount\s*\{[\s\S]*?color:\s*var\(--primary-active\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetCount\s*\{[\s\S]*?font-weight:\s*700;/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetConfirmButton\s*\{[\s\S]*?background:\s*var\(--primary-color\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetConfirmButton\s*\{[\s\S]*?color:\s*var\(--primary-contrast, #fff\);/)
    expect(credentialStyles).toMatch(/\.credentialQuotaResetConfirmButton\s*\{[\s\S]*?&:hover:not\(:disabled\)\s*\{[\s\S]*?background:\s*var\(--primary-hover\);/)
    expect(cssBlock('.credentialSectionCard:global(.ant-card)')).not.toContain('overflow: visible;')
  })

  it('keeps Auth Files quota mode and sorting above the pagination footer', () => {
    expect(authFileSectionSource).toContain('credentialQuotaActionStack')
    expect(credentialStyles).toContain('credentialQuotaActionStack')
    expect(authFileSectionSource).toContain('credentialAuthFileTableControls')
    expect(authFileSectionSource).toContain('credentials_quota_usage_mode_label')
    expect(authFileSectionSource).toContain('<Segmented<QuotaUsageMode>')
    expect(authFileSectionSource).not.toContain('leadingControls={showHealthMode')
    expect(authFileSectionSource).not.toContain('sortOptions={[')
    expect(authFileSectionSource).toContain('credentials_quota_usage_mode_current')
    expect(authFileSectionSource).toContain('credentials_quota_usage_mode_estimated')
    expect(credentialStyles).toMatch(/\.credentialAuthFileTableControls\s*\{[\s\S]*?border-bottom:/)
    expect(credentialStyles).toMatch(/\.credentialQuotaModeControl\s*\{[\s\S]*?display:\s*flex;/)
    expect(credentialStyles).not.toContain('.credentialQuotaModeSwitcher')
    expect(credentialStyles).not.toContain('.credentialQuotaModeThumbEstimated')
    expect(credentialHealthSource).toContain('HEALTH_BUCKET_MINUTES = 10')
    expect(credentialHealthSource).toContain('HEALTH_BUCKET_COUNT = HEALTH_WINDOW_MINUTES / HEALTH_BUCKET_MINUTES')
  })

  it('renders credential metrics through semantic Ant Design table columns', () => {
    expect(authFileSectionSource).toContain("const totalRequestsLabel = t('usage_stats.total_requests')")
    expect(authFileSectionSource).toContain("const sideLabel = showHealthMode ? t('usage_stats.credentials_column_health') : t('usage_stats.credentials_column_quota')")
    expect(aiProviderSectionSource).toContain("const healthLabel = t('usage_stats.credentials_column_health')")
    expect(authFileSectionSource).toMatch(/key: 'totalRequests',[\s\S]*?width: 176,[\s\S]*?key: 'successRate',[\s\S]*?width: 88,[\s\S]*?key: 'totalTokens',[\s\S]*?width: 92,[\s\S]*?key: 'cacheReadRate',[\s\S]*?width: 84,/)
    expect(aiProviderSectionSource).toMatch(/key: 'totalRequests',[\s\S]*?width: 176,[\s\S]*?key: 'successRate',[\s\S]*?width: 88,[\s\S]*?key: 'totalTokens',[\s\S]*?width: 92,[\s\S]*?key: 'cacheReadRate',[\s\S]*?width: 84,/)
    expect(credentialStyles).toMatch(/\.credentialDataTable:global\(\.ant-table-wrapper\)\s*\{[\s\S]*?:global\(\.ant-table-thead > tr > th\)\s*\{[\s\S]*?white-space:\s*nowrap;/)
    expect(credentialStyles).toMatch(/\.credentialDisplayName\s*\{[\s\S]*?text-overflow:\s*ellipsis;[\s\S]*?white-space:\s*nowrap;/)
    expect(credentialStyles).not.toContain('grid-template-columns: var(--credential-request-metric-width')
    expect(credentialShellSource).not.toContain('buildCredentialRequestMetricStyle')
    expect(credentialShellSource).not.toContain('--credential-request-metric-width')
    expect(authFileSectionSource).not.toContain('buildCredentialRequestMetricStyle')
    expect(aiProviderSectionSource).not.toContain('buildCredentialRequestMetricStyle')
    expect(credentialShellSource).not.toContain('credentialMetricLabel')
    expect(credentialStyles).toMatch(/\.credentialMetricValueCell\s*\{[\s\S]*?white-space:\s*normal;/)
    expect(credentialStyles).toMatch(/\.credentialRequestMetric\s*\{[\s\S]*?display:\s*inline-grid;/)
    expect(credentialStyles).toMatch(/\.credentialRequestMetric\s*\{[\s\S]*?grid-template-columns:\s*max-content max-content;/)
    expect(credentialStyles).toMatch(/\.credentialRequestMetric\s*\{[\s\S]*?align-items:\s*baseline;/)
    expect(credentialStyles).toMatch(/\.credentialRequestMetric\s*\{[\s\S]*?white-space:\s*nowrap;/)
    expect(credentialStyles).toMatch(/\.credentialRequestBreakdown\s*\{[\s\S]*?display:\s*inline-flex;/)
    expect(credentialStyles).toMatch(/\.credentialRequestBreakdown\s*\{[\s\S]*?white-space:\s*nowrap;/)
    expect(credentialStyles).toMatch(/\.credentialRequestBreakdown\s*\{[\s\S]*?line-height:\s*1\.2;/)
  })

  it('keeps provider filters and pagination as intentional inner scrollers', () => {
    expect(credentialShellSource).toContain('<Pagination')
    expect(credentialShellSource).toContain('<Select')
    expect(credentialShellSource).toContain('showSizeChanger')
    expect(credentialShellSource).not.toContain('<select')
    expect(credentialStyles).toMatch(/\.credentialProviderFilterBar\s*\{[\s\S]*?min-width:\s*0;[\s\S]*?max-width:\s*100%;[\s\S]*?overflow-x:\s*auto;[\s\S]*?overflow-y:\s*hidden;/)
    expect(credentialStyles).toMatch(/\.credentialPagination\s*\{[\s\S]*?min-height:\s*58px;/)
    expect(credentialStyles).toMatch(/\.credentialPagination\s*\{[\s\S]*?box-sizing:\s*border-box;/)
    expect(credentialStyles).toMatch(/\.credentialPagination\s*\{[\s\S]*?align-items:\s*center;/)
    expect(credentialStyles).toMatch(/\.credentialPagination\s*\{[\s\S]*?padding:\s*10px var\(--credential-table-inset\);/)
    expect(credentialStyles).toMatch(/\.credentialPaginationControls\s*\{[\s\S]*?width:\s*100%;/)
    expect(credentialStyles).toMatch(/\.credentialSortControl\s*\{[\s\S]*?flex:\s*0 0 auto;/)
    expect(credentialStyles).toMatch(/\.credentialSortControl\s*\{[\s\S]*?:global\(\.ant-select\)\s*\{[\s\S]*?width:\s*160px;[\s\S]*?min-width:\s*160px;/)
    expect(credentialStyles).toMatch(/@container credential-data-layout \(max-width: 1024px\)\s*\{[\s\S]*?\.credentialPagination\s*\{[\s\S]*?overflow-x:\s*auto;[\s\S]*?overflow-y:\s*hidden;[\s\S]*?max-width:\s*100%;/)
    expect(credentialStyles).toMatch(/@container credential-data-layout \(max-width: 1024px\)\s*\{[\s\S]*?\.credentialPaginationControls\s*\{[\s\S]*?width:\s*max-content;[\s\S]*?min-width:\s*100%;[\s\S]*?flex-wrap:\s*nowrap;/)
    expect(credentialStyles).not.toContain('.credentialPageSizeControl')
    expect(credentialStyles).not.toContain('--usage-pagination-bar-height')
  })

  it('keeps plan and remaining-day badges readable in dark mode', () => {
    expect(credentialStyles).toMatch(/\[data-theme='dark'\][\s\S]*\.credentialPlanBadgeTeam[\s\S]*?color:\s*#bbf7d0;/)
    expect(credentialStyles).toMatch(/\[data-theme='dark'\][\s\S]*\.credentialPlanBadgePlus[\s\S]*?color:\s*#bfdbfe;/)
    expect(credentialStyles).toMatch(/\[data-theme='dark'\][\s\S]*\.credentialPlanBadgePro[\s\S]*?color:\s*#fde68a;/)
    expect(credentialStyles).toMatch(/\[data-theme='dark'\][\s\S]*\.credentialRemainingDaysBadge[\s\S]*?color:\s*#bbf7d0;/)
  })
})
